USE [Calculators]
GO

SET IDENTITY_INSERT [dbo].[MLIAB_TokioMarineHCC_TradesmanLiability_TradePLEL_new] ON;

INSERT INTO [dbo].[MLIAB_TokioMarineHCC_TradesmanLiability_TradePLEL_new]
	(
		[TradePLELID]
		,[TradeDescriptionInsurer]
		,[TradeID]
		,[LevelOfIndemnity]
		,[AdditionalTradeLookup]
		,[PL1]
		,[PL2]
		,[PL3]
		,[PL4]
		,[PL5]
		,[PL6]
		,[PL7]
		,[PL8]
		,[PL9]
		,[PL10]
		,[EL1]
		,[ExcessProperty]
		,[ExcessHeat]
		,[Endorsement]
		,[QuestionHeat]
		,[Question3Phase]
		,[Question3PhaseRequired]
		,[QuestionPDH]
		,[QuestionPDHRequired]
		,[QuestionMaximumDepthMin]
		,[QuestionMaximumDepthMax]
		,[QuestionHeatRequired]
		,[QuestionMaximumHeightMin]
		,[QuestionMaximumHeightMax]
		,[QuestionPaving]
		,[QuestionPavingRequired]
		,[Refer]
		,[StartDatetime]
		,[EndDatetime]
		,[BusinessTransactionTypeID]
		,[Decline]
		,[InsertDateTime]
		,[InsertUserID]
		,[UpdateDateTime]
		,[UpdateUserID]
		,[DeclineNB]
		,[IsMinPremAppl]
	)
SELECT
	[TradePLELID]
    ,[TradeDescriptionInsurer]
    ,[TradeID]
    ,[LevelOfIndemnity]
    ,[AdditionalTradeLookup]
    ,[PL1]
    ,[PL2]
    ,[PL3]
    ,[PL4]
    ,[PL5]
    ,[PL6]
    ,[PL7]
    ,[PL8]
    ,[PL9]
    ,[PL10]
    ,[EL1]
    ,[ExcessProperty]
    ,[ExcessHeat]
    ,[Endorsement]
    ,[QuestionHeat]
    ,[Question3Phase]
    ,[Question3PhaseRequired]
    ,[QuestionPDH]
    ,[QuestionPDHRequired]
    ,[QuestionMaximumDepthMin]
    ,[QuestionMaximumDepthMax]
    ,[QuestionHeatRequired]
    ,[QuestionMaximumHeightMin]
    ,[QuestionMaximumHeightMax]
    ,[QuestionPaving]
    ,[QuestionPavingRequired]
    ,[Refer]
    ,[StartDatetime]
    ,[EndDatetime]
    ,[BusinessTransactionTypeID]
    ,[Decline]
    ,[InsertDateTime]
    ,[InsertUserID]
    ,[UpdateDateTime]
    ,[UpdateUserID]
    ,[DeclineNB]
    ,[IsMinPremAppl]
FROM
	[Calculators].[dbo].[MLIAB_TokioMarineHCC_TradesmanLiability_TradePLEL]

SET IDENTITY_INSERT [dbo].[MLIAB_TokioMarineHCC_TradesmanLiability_TradePLEL_new] OFF;

GO


