-- 1484 PI rows don't have a PD row with matching history ID:
SELECT * FROM [USER_MLETPROP_PROPINFO] AS [PI]
WHERE EXISTS (SELECT 1 FROM [USER_MLETPROP_PRPDTAIL] WHERE [MLETPROP_PROPINFO_ID] = [PI].[MLETPROP_PROPINFO_ID])
AND NOT EXISTS (SELECT 1 FROM [USER_MLETPROP_PRPDTAIL] WHERE [MLETPROP_PROPINFO_ID] = [PI].[MLETPROP_PROPINFO_ID] AND [HISTORY_ID] = [PI].[HISTORY_ID])
AND COVSTART > '01 Jan 2010'
ORDER BY 1, 2

-- 1483 PD rows don't have a PI row with matching history ID:
SELECT * FROM [USER_MLETPROP_PRPDTAIL] AS [PD]
WHERE EXISTS (SELECT 1 FROM [USER_MLETPROP_PROPINFO]  WHERE [MLETPROP_PROPINFO_ID] = [PD].[MLETPROP_PROPINFO_ID])
AND NOT EXISTS (SELECT 1 FROM [USER_MLETPROP_PROPINFO]  WHERE [MLETPROP_PROPINFO_ID] = [PD].[MLETPROP_PROPINFO_ID] AND [HISTORY_ID] = [PD].[HISTORY_ID])
ORDER BY 1, 2

-- View records for an example:
SELECT * FROM [USER_MLETPROP_PROPINFO] WHERE MLETPROP_PROPINFO_ID = '02B080180AFA46D68AE4B4E0A870D62A'
SELECT * FROM [USER_MLETPROP_PRPDTAIL] WHERE MLETPROP_PROPINFO_ID = '02B080180AFA46D68AE4B4E0A870D62A'