USE [Transactor_Live]
GO

SELECT * FROM [dbo].[LIST_BANK_NAME]
SELECT * FROM [dbo].[LIST_BANK_NAME_LINK]

INSERT INTO [dbo].[LIST_BANK_NAME] ([BANK_NAME_ID], [BANK_NAME_DEBUG], [DELETED], [ABIVALUE])
VALUES ('476OKEJ9', 'Starling', 0, 0)
	  ,('4771SHM9', 'Monzo', 0, 0)
;

INSERT INTO [dbo].[LIST_BANK_NAME_LINK] ([BANK_NAME_ID], [PORTFOLIOKEY], [AGENT_ID], [PRODUCT_ID], [BANK_NAME_DEFAULT])
VALUES ('476OKEJ9', 154, NULL, NULL, 0)
	  ,('4771SHM9', 154, NULL, NULL, 0)
;