SELECT * FROM [CUSTOMER_INSURED_PARTY] WHERE SURNAME = 'Greengates Construction Ltd'

SELECT [CIP].[SURNAME], [LPS].[POLICY_STATUS_DEBUG], [CPD].[POLICYNUMBER], [CPD].[POLICYSTARTDATE], [CPD].[POLICYENDDATE], * FROM [dbo].[CUSTOMER_POLICY_DETAILS] AS [CPD]
INNER JOIN [dbo].[LIST_POLICY_STATUS] AS [LPS] ON [CPD].[POLICY_STATUS_ID] = [LPS].[POLICY_STATUS_ID]
LEFT JOIN [dbo].[CUSTOMER_POLICY_LINK] AS [CPL] ON [CPD].[POLICY_DETAILS_ID] = [CPL].[POLICY_DETAILS_ID] AND [CPD].[HISTORY_ID] = [CPL].[POLICY_DETAILS_HISTORY_ID]
LEFT JOIN [dbo].[CUSTOMER_INSURED_PARTY] AS [CIP] ON [CPL].[INSURED_PARTY_ID] = [CIP].[INSURED_PARTY_ID] AND [CPL].[INSURED_PARTY_HISTORY_ID] = [CIP].[HISTORY_ID]
WHERE [CPL].INSURED_PARTY_ID = '527454DE86D54C8DBFE7A407055C39A4'
ORDER BY [CPD].[HISTORY_ID]
 
SELECT [LAT].[ACTION_LOG_TYPE_DEBUG], [RAL].*, [TVFNBREN].* FROM [dbo].[REPORT_ACTION_LOG] AS [RAL]
INNER JOIN [dbo].[LIST_ACTION_LOG_TYPE] AS [LAT] ON [RAL].[ACTIONTYPE] = [LAT].[ACTION_LOG_TYPE_ID]
OUTER APPLY [dbo].[tvfClassifyRAL_NB_REN] ([RAL].[ACTION_LOG_ID]) AS [TVFNBREN]
WHERE [RAL].[POLICY_DETAILS_ID] = '1775CBD28EB0401991C584F68CDF9EB2'
ORDER BY [RAL].[ACTIONDATE]

UPDATE [CUSTOMER_POLICY_DETAILS]
SET [POLICY_STATUS_ID] = '3AJPUL67' -- Prospect
WHERE [POLICY_DETAILS_ID] = '1775CBD28EB0401991C584F68CDF9EB2'