USE [Transactor_Live]
GO

-- SELECT * FROM [Transactor_Live].[dbo].[LIST_MH_TRADE_LINK]

--SELECT * FROM RM_AGENT

--select * from rm_product

--Finding Trades in CAQ but not in MHG
--SELECT *
--FROM [LIST_MH_TRADE] 
--WHERE MH_TRADE_ID IN (
--     SELECT CAQ.MH_TRADE_ID
--     FROM LIST_MH_TRADE_LINK AS CAQ
--     LEFT JOIN LIST_MH_TRADE_LINK AS MHG
--     ON CAQ.MH_TRADE_ID = MHG.MH_TRADE_ID
--     AND CAQ.PRODUCT_ID = MHG.PRODUCT_ID
--     AND MHG.AGENT_ID = '83512274B9F14EBF9B4F81DE2591EC80'
--     WHERE CAQ.AGENT_ID = 'E2F376B621E14C1FB532CED74C7EDCE1'
--     AND CAQ.PRODUCT_ID = '4318A62733AD444DBBA0AB2A586D5021'
--     AND MHG.MH_TRADE_ID IS NULL
-- ORDER BY MH_TRADE_DEBUG;


SELECT * FROM [Transactor_Live].[dbo].[LIST_MH_TRADE_LINK]

-- Moorhouse Group Limited
--264 rows inserted
--Finding Trades in CAQ but not in MHG, AND Inserting them for the MHG agent
INSERT INTO [Transactor_Live].[dbo].[LIST_MH_TRADE_LINK] (MH_TRADE_ID, PORTFOLIOKEY, AGENT_ID, PRODUCT_ID, MH_TRADE_DEFAULT)
SELECT LMT.MH_TRADE_ID, 154, '83512274B9F14EBF9B4F81DE2591EC80', CAQ.PRODUCT_ID, 0 
FROM [LIST_MH_TRADE] AS LMT
JOIN LIST_MH_TRADE_LINK AS CAQ ON CAQ.MH_TRADE_ID = LMT.MH_TRADE_ID
LEFT JOIN LIST_MH_TRADE_LINK AS MHG ON CAQ.MH_TRADE_ID = MHG.MH_TRADE_ID
AND CAQ.PRODUCT_ID = MHG.PRODUCT_ID
AND MHG.AGENT_ID = '83512274B9F14EBF9B4F81DE2591EC80' -- MHG
WHERE CAQ.AGENT_ID = 'E2F376B621E14C1FB532CED74C7EDCE1' -- CAQ
AND CAQ.PRODUCT_ID = '4318A62733AD444DBBA0AB2A586D5021' -- Prof Indemnity
 AND MHG.MH_TRADE_ID IS NULL
 ORDER BY LMT.MH_TRADE_DEBUG;

 --== Caq.com

 --Finding Trades in CAQ but not in Caq.com, AND Inserting them for the Caq.com agent
--INSERT INTO [Transactor_Live].[dbo].[LIST_MH_TRADE_LINK] (MH_TRADE_ID, PORTFOLIOKEY, AGENT_ID, PRODUCT_ID, MH_TRADE_DEFAULT)
SELECT LMT.MH_TRADE_ID, 154, '5208F39A498E4706A91BEEC84ED25686', CAQ.PRODUCT_ID, 0 
FROM [LIST_MH_TRADE] AS LMT
JOIN LIST_MH_TRADE_LINK AS CAQ ON CAQ.MH_TRADE_ID = LMT.MH_TRADE_ID
LEFT JOIN LIST_MH_TRADE_LINK AS CAQCOM ON CAQ.MH_TRADE_ID = CAQCOM.MH_TRADE_ID
AND CAQ.PRODUCT_ID = CAQCOM.PRODUCT_ID
AND CAQCOM.AGENT_ID = '5208F39A498E4706A91BEEC84ED25686' -- Caq.com
WHERE CAQ.AGENT_ID = 'E2F376B621E14C1FB532CED74C7EDCE1' -- CAQ
AND CAQ.PRODUCT_ID = '4318A62733AD444DBBA0AB2A586D5021' -- Prof Indemnity
 AND CAQCOM.MH_TRADE_ID IS NULL
 ORDER BY LMT.MH_TRADE_DEBUG;

 --==Xbroker

  --Finding Trades in CAQ but not in Xbroker, AND Inserting them for the Xbroker agent
--INSERT INTO [Transactor_Live].[dbo].[LIST_MH_TRADE_LINK] (MH_TRADE_ID, PORTFOLIOKEY, AGENT_ID, PRODUCT_ID, MH_TRADE_DEFAULT)
SELECT LMT.MH_TRADE_ID, 154, '0F849A389DD4477CAF66BBCBECA49AA4', CAQ.PRODUCT_ID, 0 
FROM [LIST_MH_TRADE] AS LMT
JOIN LIST_MH_TRADE_LINK AS CAQ ON CAQ.MH_TRADE_ID = LMT.MH_TRADE_ID
LEFT JOIN LIST_MH_TRADE_LINK AS Xbrkr ON CAQ.MH_TRADE_ID = Xbrkr.MH_TRADE_ID
AND CAQ.PRODUCT_ID = Xbrkr.PRODUCT_ID
AND Xbrkr.AGENT_ID = '0F849A389DD4477CAF66BBCBECA49AA4' -- Xbroker
WHERE CAQ.AGENT_ID = 'E2F376B621E14C1FB532CED74C7EDCE1' -- CAQ
AND CAQ.PRODUCT_ID = '4318A62733AD444DBBA0AB2A586D5021' -- Prof Indemnity
 AND Xbrkr.MH_TRADE_ID IS NULL
 ORDER BY LMT.MH_TRADE_DEBUG;

