<%@ Page Language="VB" MasterPageFile="~/ScreenLOBSingle.master" AutoEventWireup="false" Inherits="clsCorePage" %>
<%@ Register Src="../PostcodeSearch.ascx" TagName="PostcodeSearch" TagPrefix="uc1" %>
<%@ Register Src="../vehiclesearch.ascx" TagName="VehicleSearch" TagPrefix="uc2" %>
<%@ Register TagPrefix="tes_webcontrols" Namespace="TES_WebControls" Assembly="TES_WebControls" %>
<asp:Content ID="Content1" ContentPlaceHolderID="LOBPageName" Runat="Server">
 <h1 id="pageHeading" runat="server">Personal Accident and Income Protection</h1>
 <div id="pageDescription" runat="server" visible="false"></div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="LOBData" Runat="Server">
 <div class="datacapture">
     <fieldset>
         <legend>Personal Accident and Income Protection</legend>
         <ol class="formlayout">
             <li id="subUSER_MLIAB_ACCINCOM__COVERYN__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_ACCINCOM__COVERYN__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_ACCINCOM__COVERYN__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_ACCINCOM__COVERYN__0" runat="server" AssociatedControlID="USER_MLIAB_ACCINCOM__COVERYN__0">PersonalAccident</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLYNRadioSelect ID="USER_MLIAB_ACCINCOM__COVERYN__0" runat="server" renderWithoutTable="true"><relatedControl ctl="USER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0_ctl" type="enable" YesValue="True" page="accincom.aspx" /><relatedControl ctl="pUSER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0" type="visible" YesValue="True" page="accincom.aspx" /><relatedControl ctl="subUSER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0" type="visible" YesValue="True" page="accincom.aspx" /><relatedControl ctl="USER_MLIAB_ACCINCOM__INCOMECOVER_ID__0_ctl" type="enable" YesValue="True" page="accincom.aspx" /><relatedControl ctl="pUSER_MLIAB_ACCINCOM__INCOMECOVER_ID__0" type="visible" YesValue="True" page="accincom.aspx" /><relatedControl ctl="subUSER_MLIAB_ACCINCOM__INCOMECOVER_ID__0" type="visible" YesValue="True" page="accincom.aspx" /><relatedControl ctl="USER_MLIAB_ACCINCOM__PEOPLENUM__0_ctl" type="enable" YesValue="True" page="accincom.aspx" /><relatedControl ctl="pUSER_MLIAB_ACCINCOM__PEOPLENUM__0" type="visible" YesValue="True" page="accincom.aspx" /><relatedControl ctl="subUSER_MLIAB_ACCINCOM__PEOPLENUM__0" type="visible" YesValue="True" page="accincom.aspx" /></tes_webcontrols:TGSLYNRadioSelect>&nbsp;<span class="GlossaryTerm" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_ACCINCOM__COVERYN__0');"><tes_webcontrols:tgslimage id="imgHLP_USER_MLIAB_ACCINCOM__COVERYN__0" runat="server" CssClass="helpimg" UseBranding="True" ImageFileName="help.gif" ImageUrl="~/images/help.gif" alt="Click here for help" /></span><div class="HelpDiv" id="hlpUSER_MLIAB_ACCINCOM__COVERYN__0" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_ACCINCOM__COVERYN__0');"><span class="helptitle" id="HelpTitle1" runat="server">PersonalAccident</span><span class="helpclose">Close</span><span class="helptext">Include Personal Accident and Income Protection Cover</span></div>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_ACCINCOM__COVERYN__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_ACCINCOM__COVERYN__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="PersonalAccident" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0" runat="server" AssociatedControlID="USER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0">coverLevel</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLGetListDropDown id="USER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0" runat="server" ListViewName="mh_personalaccidentlevel_view"></tes_webcontrols:TGSLGetListDropDown>&nbsp;<span class="GlossaryTerm" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0');"><tes_webcontrols:tgslimage id="imgHLP_USER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0" runat="server" CssClass="helpimg" UseBranding="True" ImageFileName="help.gif" ImageUrl="~/images/help.gif" alt="Click here for help" /></span><div class="HelpDiv" id="hlpUSER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0');"><span class="helptitle" id="HelpTitle2" runat="server">coverLevel</span><span class="helpclose">Close</span><span class="helptext">Personal Accident Cover Level</span></div>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_ACCINCOM__ACCIDENTCOVER_ID__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="coverLevel" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_ACCINCOM__INCOMECOVER_ID__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_ACCINCOM__INCOMECOVER_ID__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_ACCINCOM__INCOMECOVER_ID__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_ACCINCOM__INCOMECOVER_ID__0" runat="server" AssociatedControlID="USER_MLIAB_ACCINCOM__INCOMECOVER_ID__0">Income Cover</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLGetListDropDown id="USER_MLIAB_ACCINCOM__INCOMECOVER_ID__0" runat="server" ListViewName="mh_paincomeprotectionlevel_view"></tes_webcontrols:TGSLGetListDropDown>&nbsp;<span class="GlossaryTerm" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_ACCINCOM__INCOMECOVER_ID__0');"><tes_webcontrols:tgslimage id="imgHLP_USER_MLIAB_ACCINCOM__INCOMECOVER_ID__0" runat="server" CssClass="helpimg" UseBranding="True" ImageFileName="help.gif" ImageUrl="~/images/help.gif" alt="Click here for help" /></span><div class="HelpDiv" id="hlpUSER_MLIAB_ACCINCOM__INCOMECOVER_ID__0" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_ACCINCOM__INCOMECOVER_ID__0');"><span class="helptitle" id="HelpTitle3" runat="server">Income Cover</span><span class="helpclose">Close</span><span class="helptext">Income Protection Cover Level</span></div>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_ACCINCOM__INCOMECOVER_ID__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_ACCINCOM__INCOMECOVER_ID__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="Income Cover" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_ACCINCOM__PEOPLENUM__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_ACCINCOM__PEOPLENUM__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_ACCINCOM__PEOPLENUM__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_ACCINCOM__PEOPLENUM__0" runat="server" AssociatedControlID="USER_MLIAB_ACCINCOM__PEOPLENUM__0">PeopleNum</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLTextBox id="USER_MLIAB_ACCINCOM__PEOPLENUM__0" runat="server" MaxLength="32767"  Numeric="True" ><relatedControl ctl="USER_MLIAB_PAPEOPLE__TITLE_ID__0_ctl" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="lblUSER_MLIAB_PAPEOPLE__TITLE_ID__0" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="USER_MLIAB_PAPEOPLE__DATEOFBIRTH__0_cboDay" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="USER_MLIAB_PAPEOPLE__DATEOFBIRTH__0_cboMonth" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="USER_MLIAB_PAPEOPLE__DATEOFBIRTH__0_cboYear" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="lblUSER_MLIAB_PAPEOPLE__DATEOFBIRTH__0" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="USER_MLIAB_PAPEOPLE__UKRESIDENTYN__0" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="lblUSER_MLIAB_PAPEOPLE__UKRESIDENTYN__0" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="USER_MLIAB_PAPEOPLE__FORENAMES__0_ctl" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="lblUSER_MLIAB_PAPEOPLE__FORENAMES__0" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="USER_MLIAB_PAPEOPLE__SURNAME__0_ctl" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /><relatedControl ctl="lblUSER_MLIAB_PAPEOPLE__SURNAME__0" type="enable" symbol="Greater" threshold="0" enable="True" page="papeople.aspx" /></tes_webcontrols:TGSLTextBox>&nbsp;<span class="GlossaryTerm" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_ACCINCOM__PEOPLENUM__0');"><tes_webcontrols:tgslimage id="imgHLP_USER_MLIAB_ACCINCOM__PEOPLENUM__0" runat="server" CssClass="helpimg" UseBranding="True" ImageFileName="help.gif" ImageUrl="~/images/help.gif" alt="Click here for help" /></span><div class="HelpDiv" id="hlpUSER_MLIAB_ACCINCOM__PEOPLENUM__0" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_ACCINCOM__PEOPLENUM__0');"><span class="helptitle" id="HelpTitle4" runat="server">PeopleNum</span><span class="helpclose">Close</span><span class="helptext">Number of Employees Covered by Personal Accident and Income Protection</span></div>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_ACCINCOM__PEOPLENUM__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_ACCINCOM__PEOPLENUM__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="PeopleNum" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
         </ol>
     </fieldset>
 </div>
</asp:Content>
