<%@ Page Language="VB" MasterPageFile="~/ScreenLOBSingle.master" AutoEventWireup="false" Inherits="clsCorePage" %>
<%@ Register Src="../PostcodeSearch.ascx" TagName="PostcodeSearch" TagPrefix="uc1" %>
<%@ Register Src="../vehiclesearch.ascx" TagName="VehicleSearch" TagPrefix="uc2" %>
<%@ Register TagPrefix="tes_webcontrols" Namespace="TES_WebControls" Assembly="TES_WebControls" %>
<asp:Content ID="Content1" ContentPlaceHolderID="LOBPageName" Runat="Server">
 <h1 id="pageHeading" runat="server">Business Support</h1>
 <div id="pageDescription" runat="server" visible="false"></div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="LOBData" Runat="Server">
 <div class="datacapture">
     <fieldset>
         <legend>Business Support</legend>
         <ol class="formlayout">
             <li id="subUSER_MLIAB_BUSSUPP__BUSSUPPCOVER__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__BUSSUPPCOVER__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__BUSSUPPCOVER__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__BUSSUPPCOVER__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__BUSSUPPCOVER__0">Do you require Business Support Cover?</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLYNRadioSelect ID="USER_MLIAB_BUSSUPP__BUSSUPPCOVER__0" runat="server" renderWithoutTable="true"><relatedControl ctl="USER_MLIAB_BUSSUPP__EMPS__0_ctl" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__EMPS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__EMPS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="USER_MLIAB_BUSSUPP__EMPDISPUTE__0" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__EMPDISPUTE__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__EMPDISPUTE__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="USER_MLIAB_BUSSUPP__REDUNDANCIES__0" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__REDUNDANCIES__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__REDUNDANCIES__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="USER_MLIAB_BUSSUPP__REGULATIONS__0" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__REGULATIONS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__REGULATIONS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="USER_MLIAB_BUSSUPP__DISCUSSIONS__0" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__DISCUSSIONS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__DISCUSSIONS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="USER_MLIAB_BUSSUPP__TRIBUNAL__0" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__TRIBUNAL__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__TRIBUNAL__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="USER_MLIAB_BUSSUPP__HANDS__0" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__HANDS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__HANDS__0" type="visible" YesValue="True" page="bussupp.aspx" /></tes_webcontrols:TGSLYNRadioSelect>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__BUSSUPPCOVER__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__BUSSUPPCOVER__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="Do you require Business Support Cover?" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__EMPS__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__EMPS__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__EMPS__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__EMPS__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__EMPS__0">How many employees do you have?</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLTextBox id="USER_MLIAB_BUSSUPP__EMPS__0" runat="server" MaxLength="3"  Numeric="True" ></tes_webcontrols:TGSLTextBox>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__EMPS__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__EMPS__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="How many employees do you have?" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__EMPDISPUTE__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__EMPDISPUTE__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__EMPDISPUTE__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__EMPDISPUTE__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__EMPDISPUTE__0">employment dispute claim</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLYNRadioSelect ID="USER_MLIAB_BUSSUPP__EMPDISPUTE__0" runat="server" renderWithoutTable="true"><relatedControl ctl="USER_MLIAB_BUSSUPP__EMPDISDETAILS__0_ctl" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__EMPDISDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__EMPDISDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /></tes_webcontrols:TGSLYNRadioSelect>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__EMPDISPUTE__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__EMPDISPUTE__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="employment dispute claim" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__EMPDISDETAILS__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__EMPDISDETAILS__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__EMPDISDETAILS__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__EMPDISDETAILS__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__EMPDISDETAILS__0">If yes, please provide details</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLTextBox id="USER_MLIAB_BUSSUPP__EMPDISDETAILS__0" runat="server" MaxLength="100" ></tes_webcontrols:TGSLTextBox>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__EMPDISDETAILS__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__EMPDISDETAILS__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="If yes, please provide details" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__REDUNDANCIES__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__REDUNDANCIES__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__REDUNDANCIES__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__REDUNDANCIES__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__REDUNDANCIES__0">made any redundancies</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLYNRadioSelect ID="USER_MLIAB_BUSSUPP__REDUNDANCIES__0" runat="server" renderWithoutTable="true"><relatedControl ctl="USER_MLIAB_BUSSUPP__REDUNDETAILS__0_ctl" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__REDUNDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__REDUNDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /></tes_webcontrols:TGSLYNRadioSelect>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__REDUNDANCIES__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__REDUNDANCIES__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="made any redundancies" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__REDUNDETAILS__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__REDUNDETAILS__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__REDUNDETAILS__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__REDUNDETAILS__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__REDUNDETAILS__0">If yes, please provide details</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLTextBox id="USER_MLIAB_BUSSUPP__REDUNDETAILS__0" runat="server" MaxLength="100" ></tes_webcontrols:TGSLTextBox>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__REDUNDETAILS__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__REDUNDETAILS__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="If yes, please provide details" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__REGULATIONS__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__REGULATIONS__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__REGULATIONS__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__REGULATIONS__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__REGULATIONS__0">breaching any employment regulations</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLYNRadioSelect ID="USER_MLIAB_BUSSUPP__REGULATIONS__0" runat="server" renderWithoutTable="true"><relatedControl ctl="USER_MLIAB_BUSSUPP__REGUDETAILS__0_ctl" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__REGUDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__REGUDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /></tes_webcontrols:TGSLYNRadioSelect>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__REGULATIONS__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__REGULATIONS__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="breaching any employment regulations" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__REGUDETAILS__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__REGUDETAILS__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__REGUDETAILS__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__REGUDETAILS__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__REGUDETAILS__0">If yes, please provide details</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLTextBox id="USER_MLIAB_BUSSUPP__REGUDETAILS__0" runat="server" MaxLength="100" ></tes_webcontrols:TGSLTextBox>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__REGUDETAILS__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__REGUDETAILS__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="If yes, please provide details" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__DISCUSSIONS__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__DISCUSSIONS__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__DISCUSSIONS__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__DISCUSSIONS__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__DISCUSSIONS__0">discussions with any party in respect of</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLYNRadioSelect ID="USER_MLIAB_BUSSUPP__DISCUSSIONS__0" runat="server" renderWithoutTable="true"><relatedControl ctl="USER_MLIAB_BUSSUPP__DISCUSSDETAILS__0_ctl" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__DISCUSSDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__DISCUSSDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /></tes_webcontrols:TGSLYNRadioSelect>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__DISCUSSIONS__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__DISCUSSIONS__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="discussions with any party in respect of" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__DISCUSSDETAILS__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__DISCUSSDETAILS__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__DISCUSSDETAILS__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__DISCUSSDETAILS__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__DISCUSSDETAILS__0">If yes, please provide details</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLTextBox id="USER_MLIAB_BUSSUPP__DISCUSSDETAILS__0" runat="server" MaxLength="100" ></tes_webcontrols:TGSLTextBox>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__DISCUSSDETAILS__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__DISCUSSDETAILS__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="If yes, please provide details" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__TRIBUNAL__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__TRIBUNAL__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__TRIBUNAL__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__TRIBUNAL__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__TRIBUNAL__0">employment tribunal or court proceedings</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLYNRadioSelect ID="USER_MLIAB_BUSSUPP__TRIBUNAL__0" runat="server" renderWithoutTable="true"><relatedControl ctl="USER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0_ctl" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /></tes_webcontrols:TGSLYNRadioSelect>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__TRIBUNAL__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__TRIBUNAL__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="employment tribunal or court proceedings" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0">If yes, please provide details</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLTextBox id="USER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0" runat="server" MaxLength="100" ></tes_webcontrols:TGSLTextBox>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__TRIBUNALDETAILS__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="If yes, please provide details" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__HANDS__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__HANDS__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__HANDS__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__HANDS__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__HANDS__0">prosecution under the health and safety</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLYNRadioSelect ID="USER_MLIAB_BUSSUPP__HANDS__0" runat="server" renderWithoutTable="true"><relatedControl ctl="USER_MLIAB_BUSSUPP__HANDSDETAILS__0_ctl" type="enable" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="pUSER_MLIAB_BUSSUPP__HANDSDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /><relatedControl ctl="subUSER_MLIAB_BUSSUPP__HANDSDETAILS__0" type="visible" YesValue="True" page="bussupp.aspx" /></tes_webcontrols:TGSLYNRadioSelect>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__HANDS__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__HANDS__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="prosecution under the health and safety" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_BUSSUPP__HANDSDETAILS__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_BUSSUPP__HANDSDETAILS__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_BUSSUPP__HANDSDETAILS__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_BUSSUPP__HANDSDETAILS__0" runat="server" AssociatedControlID="USER_MLIAB_BUSSUPP__HANDSDETAILS__0">If yes, please provide details</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLTextBox id="USER_MLIAB_BUSSUPP__HANDSDETAILS__0" runat="server" MaxLength="100" ></tes_webcontrols:TGSLTextBox>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_BUSSUPP__HANDSDETAILS__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_BUSSUPP__HANDSDETAILS__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="If yes, please provide details" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
         </ol>
     </fieldset>
 </div>
</asp:Content>
