<%@ Page Language="VB" MasterPageFile="~/ScreenLOBMultiple.master" AutoEventWireup="false" Inherits="clsCorePage" %>
<%@ Register Src="../PostcodeSearch.ascx" TagName="PostcodeSearch" TagPrefix="uc1" %>
<%@ Register Src="../vehiclesearch.ascx" TagName="VehicleSearch" TagPrefix="uc2" %>
<%@ Register TagPrefix="tes_webcontrols" Namespace="TES_WebControls" Assembly="TES_WebControls" %>
<asp:Content ID="Content1" ContentPlaceHolderID="LOBPageName" Runat="Server">
 <h1 id="pageHeading" runat="server">Personal Accident and Income People</h1>
 <div id="pageDescription" runat="server" visible="false"></div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="LOBData" Runat="Server">
 <div class="datacapture">
     <fieldset>
         <legend>Personal Accident and Income People</legend>
         <ol class="formlayout">
             <li id="subUSER_MLIAB_PAPEOPLE__TITLE_ID__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_PAPEOPLE__TITLE_ID__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_PAPEOPLE__TITLE_ID__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_PAPEOPLE__TITLE_ID__0" runat="server" AssociatedControlID="USER_MLIAB_PAPEOPLE__TITLE_ID__0">Title</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLGetListDropDown id="USER_MLIAB_PAPEOPLE__TITLE_ID__0" runat="server" ListViewName="title_view"></tes_webcontrols:TGSLGetListDropDown>&nbsp;<span class="GlossaryTerm" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_PAPEOPLE__TITLE_ID__0');"><tes_webcontrols:tgslimage id="imgHLP_USER_MLIAB_PAPEOPLE__TITLE_ID__0" runat="server" CssClass="helpimg" UseBranding="True" ImageFileName="help.gif" ImageUrl="~/images/help.gif" alt="Click here for help" /></span><div class="HelpDiv" id="hlpUSER_MLIAB_PAPEOPLE__TITLE_ID__0" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_PAPEOPLE__TITLE_ID__0');"><span class="helptitle" id="HelpTitle1" runat="server">Title</span><span class="helpclose">Close</span><span class="helptext">Mr, Mrs, Dr etc..</span></div>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_PAPEOPLE__TITLE_ID__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_PAPEOPLE__TITLE_ID__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="Title" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_PAPEOPLE__FORENAMES__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_PAPEOPLE__FORENAMES__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_PAPEOPLE__FORENAMES__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_PAPEOPLE__FORENAMES__0" runat="server" AssociatedControlID="USER_MLIAB_PAPEOPLE__FORENAMES__0">Forenames</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLTextBox id="USER_MLIAB_PAPEOPLE__FORENAMES__0" runat="server" MaxLength="50" ></tes_webcontrols:TGSLTextBox>&nbsp;<span class="GlossaryTerm" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_PAPEOPLE__FORENAMES__0');"><tes_webcontrols:tgslimage id="imgHLP_USER_MLIAB_PAPEOPLE__FORENAMES__0" runat="server" CssClass="helpimg" UseBranding="True" ImageFileName="help.gif" ImageUrl="~/images/help.gif" alt="Click here for help" /></span><div class="HelpDiv" id="hlpUSER_MLIAB_PAPEOPLE__FORENAMES__0" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_PAPEOPLE__FORENAMES__0');"><span class="helptitle" id="HelpTitle2" runat="server">Forenames</span><span class="helpclose">Close</span><span class="helptext">First Name</span></div>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_PAPEOPLE__FORENAMES__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_PAPEOPLE__FORENAMES__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="Forenames" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_PAPEOPLE__SURNAME__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_PAPEOPLE__SURNAME__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_PAPEOPLE__SURNAME__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_PAPEOPLE__SURNAME__0" runat="server" AssociatedControlID="USER_MLIAB_PAPEOPLE__SURNAME__0">Surname</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLTextBox id="USER_MLIAB_PAPEOPLE__SURNAME__0" runat="server" MaxLength="50" ></tes_webcontrols:TGSLTextBox>&nbsp;<span class="GlossaryTerm" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_PAPEOPLE__SURNAME__0');"><tes_webcontrols:tgslimage id="imgHLP_USER_MLIAB_PAPEOPLE__SURNAME__0" runat="server" CssClass="helpimg" UseBranding="True" ImageFileName="help.gif" ImageUrl="~/images/help.gif" alt="Click here for help" /></span><div class="HelpDiv" id="hlpUSER_MLIAB_PAPEOPLE__SURNAME__0" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_PAPEOPLE__SURNAME__0');"><span class="helptitle" id="HelpTitle3" runat="server">Surname</span><span class="helpclose">Close</span><span class="helptext">Last Name</span></div>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_PAPEOPLE__SURNAME__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_PAPEOPLE__SURNAME__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="Surname" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_PAPEOPLE__DATEOFBIRTH__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_PAPEOPLE__DATEOFBIRTH__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_PAPEOPLE__DATEOFBIRTH__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_PAPEOPLE__DATEOFBIRTH__0" runat="server" AssociatedControlID="USER_MLIAB_PAPEOPLE__DATEOFBIRTH__0">DateOfBirth</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLDateSelect id="USER_MLIAB_PAPEOPLE__DATEOFBIRTH__0" runat="server"></tes_webcontrols:TGSLDateSelect>&nbsp;<span class="GlossaryTerm" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_PAPEOPLE__DATEOFBIRTH__0');"><tes_webcontrols:tgslimage id="imgHLP_USER_MLIAB_PAPEOPLE__DATEOFBIRTH__0" runat="server" CssClass="helpimg" UseBranding="True" ImageFileName="help.gif" ImageUrl="~/images/help.gif" alt="Click here for help" /></span><div class="HelpDiv" id="hlpUSER_MLIAB_PAPEOPLE__DATEOFBIRTH__0" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_PAPEOPLE__DATEOFBIRTH__0');"><span class="helptitle" id="HelpTitle4" runat="server">DateOfBirth</span><span class="helpclose">Close</span><span class="helptext">Date of Birth</span></div>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_PAPEOPLE__DATEOFBIRTH__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_PAPEOPLE__DATEOFBIRTH__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="DateOfBirth" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
             <li id="subUSER_MLIAB_PAPEOPLE__UKRESIDENTYN__0" runat="server" style="display:none;"></li>
             <li id="pUSER_MLIAB_PAPEOPLE__UKRESIDENTYN__0">
                 <span class="required"><tes_webcontrols:tgslimage id="imgUSER_MLIAB_PAPEOPLE__UKRESIDENTYN__0" runat="server" UseBranding="True" ImageFileName="required.gif" ImageUrl="~/images/required.gif"></tes_webcontrols:tgslimage></span>
                 <tes_webcontrols:TGSLLabel ID="lblUSER_MLIAB_PAPEOPLE__UKRESIDENTYN__0" runat="server" AssociatedControlID="USER_MLIAB_PAPEOPLE__UKRESIDENTYN__0">optUKResidentYN</tes_webcontrols:TGSLLabel>
                 <span class="control"><tes_webcontrols:TGSLYNRadioSelect ID="USER_MLIAB_PAPEOPLE__UKRESIDENTYN__0" runat="server" renderWithoutTable="true"></tes_webcontrols:TGSLYNRadioSelect>&nbsp;<span class="GlossaryTerm" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_PAPEOPLE__UKRESIDENTYN__0');"><tes_webcontrols:tgslimage id="imgHLP_USER_MLIAB_PAPEOPLE__UKRESIDENTYN__0" runat="server" CssClass="helpimg" UseBranding="True" ImageFileName="help.gif" ImageUrl="~/images/help.gif" alt="Click here for help" /></span><div class="HelpDiv" id="hlpUSER_MLIAB_PAPEOPLE__UKRESIDENTYN__0" onclick="ToggleDivDisplay(event, 'hlpUSER_MLIAB_PAPEOPLE__UKRESIDENTYN__0');"><span class="helptitle" id="HelpTitle5" runat="server">optUKResidentYN</span><span class="helpclose">Close</span><span class="helptext">Permanent resident of the UK</span></div>&nbsp;<tes_webcontrols:TGSLRequiredValidator ID="reqUSER_MLIAB_PAPEOPLE__UKRESIDENTYN__0" runat="server" Branded="False" ControlToValidate="USER_MLIAB_PAPEOPLE__UKRESIDENTYN__0" Display="Dynamic" ShowMandatory="False" EnableClientScript="False" ErrorMessage="optUKResidentYN" Override="True" OverrideErrorMessage="*Required"></tes_webcontrols:TGSLRequiredValidator></span>
             </li>
         </ol>
     </fieldset>
 </div>
</asp:Content>
