--SELECT * FROM [CUSTOMER_INSURED_PARTY] WHERE [SURNAME] = 'Tollgate Engineering Services Ltd'

-- Policy, RAL and transaction history
 
DECLARE @POLICY_DETAILS_ID TABLE ([POLICY_DETAILS_ID] char(32)) 
--INSERT INTO @POLICY_DETAILS_ID SELECT DISTINCT [POLICY_DETAILS_ID] FROM [CUSTOMER_POLICY_DETAILS] WHERE [POLICYNUMBER] = 'TISBXBPO1000015' -- Neil Marcus Construction Limited
INSERT INTO @POLICY_DETAILS_ID SELECT DISTINCT [POLICY_DETAILS_ID] FROM [CUSTOMER_POLICY_DETAILS] WHERE [POLICYNUMBER] = 'ALCFL1000105' -- Tollgate Engineering Services Ltd
--INSERT INTO @POLICY_DETAILS_ID SELECT DISTINCT [POLICY_DETAILS_ID] FROM [CUSTOMER_POLICY_DETAILS] WHERE [POLICYNUMBER] = 'AVIPO1000380' -- White Mice Estates Limited

SELECT [CIP].[SURNAME], [LPS].[POLICY_STATUS_DEBUG], [CPD].[POLICYSTARTDATE], [CPD].[POLICYENDDATE], * FROM [dbo].[CUSTOMER_POLICY_DETAILS] AS [CPD]
INNER JOIN [dbo].[LIST_POLICY_STATUS] AS [LPS] ON [CPD].[POLICY_STATUS_ID] = [LPS].[POLICY_STATUS_ID]
LEFT JOIN [dbo].[CUSTOMER_POLICY_LINK] AS [CPL] ON [CPD].[POLICY_DETAILS_ID] = [CPL].[POLICY_DETAILS_ID] AND [CPD].[HISTORY_ID] = [CPL].[POLICY_DETAILS_HISTORY_ID]
LEFT JOIN [dbo].[CUSTOMER_INSURED_PARTY] AS [CIP] ON [CPL].[INSURED_PARTY_ID] = [CIP].[INSURED_PARTY_ID] AND [CPL].[INSURED_PARTY_HISTORY_ID] = [CIP].[HISTORY_ID]
WHERE [CPD].[POLICY_DETAILS_ID] IN (SELECT [POLICY_DETAILS_ID] FROM @POLICY_DETAILS_ID)
--WHERE [CIP].[SURNAME] = 'White Mice Estates Limited'
ORDER BY [CPD].[HISTORY_ID]
 
SELECT [LAT].[ACTION_LOG_TYPE_DEBUG], [RAL].*, [TVFNBREN].* FROM [dbo].[REPORT_ACTION_LOG] AS [RAL]
INNER JOIN [dbo].[LIST_ACTION_LOG_TYPE] AS [LAT] ON [RAL].[ACTIONTYPE] = [LAT].[ACTION_LOG_TYPE_ID]
OUTER APPLY [dbo].[tvfClassifyRAL_NB_REN] ([RAL].[ACTION_LOG_ID]) AS [TVFNBREN]
WHERE [RAL].[POLICY_DETAILS_ID] IN (SELECT [POLICY_DETAILS_ID] FROM @POLICY_DETAILS_ID)
AND [RAL].[ACTIONTYPE] NOT IN (6, 43) -- Amend, ClientContact
ORDER BY [RAL].[ACTIONDATE]
 
-- Transactions by Policy history
--DECLARE @POLICY_DETAILS_ID char(32) = (SELECT DISTINCT POLICY_DETAILS_ID FROM CUSTOMER_POLICY_DETAILS WHERE POLICYNUMBER = 'COMCP1000811')
 
SELECT
	 [ACTL].[POLICY_DETAILS_ID]
	,[ACTL].[POLICY_DETAILS_HISTORY_ID]
	,SUM(CASE WHEN [ATB].[TRAN_BREAKDOWN_TYPE_ID] IN ('NET') THEN [ATB].[AMOUNT] END) AS GWP
	,SUM(CASE WHEN [ATB].[TRAN_BREAKDOWN_TYPE_ID] IN ('TAX_IPT') THEN [ATB].[AMOUNT] END) AS IPT
	,SUM(CASE WHEN [ATB].[TRAN_BREAKDOWN_TYPE_ID] IN ('BRKCOMMF','BRKCOMMP') THEN [ATB].[AMOUNT] END) AS [Brokerage]
	,SUM(CASE WHEN [ATB].[TRAN_BREAKDOWN_TYPE_ID] IN ('BRKDISCF','BRKDISCP') THEN [ATB].[AMOUNT] END) AS [Discount]
	,SUM(CASE WHEN [ATB].[TRAN_BREAKDOWN_TYPE_ID] IN ('SUBCOMMF','SUBCOMMP') THEN [ATB].[AMOUNT] END) AS [SubagentCommission]
	,SUM(CASE WHEN [ATB].[TRAN_BREAKDOWN_TYPE_ID] IN ('FEE') THEN [ATB].[AMOUNT] END) AS [Fee]
FROM
	[dbo].[ACCOUNTS_TRAN_BREAKDOWN] AS [ATB]
	INNER JOIN [dbo].[ACCOUNTS_CLIENT_TRAN_LINK] AS [ACTL] ON  [ATB].[TRANSACTION_ID] = [ACTL].[TRANSACTION_ID]
WHERE [ACTL].[POLICY_DETAILS_ID] IN (SELECT [POLICY_DETAILS_ID] FROM @POLICY_DETAILS_ID)
GROUP BY
	 [ACTL].[POLICY_DETAILS_ID]
	,[ACTL].[POLICY_DETAILS_HISTORY_ID]
 
-- Transaction detail
SELECT
	 [AT].[PAYMENTDATE]
	,[ACTL].[POLICY_DETAILS_ID]
	,[ACTL].[POLICY_DETAILS_HISTORY_ID]
	,[AT].[TRANSACTION_REASON_ID]
	,[AT].[TRANSACTION_CODE_ID]
	,[ATB].[TRAN_BREAKDOWN_TYPE_ID]
	,[ATB].[AMOUNT]
FROM
	[dbo].[ACCOUNTS_TRANSACTION] AS [AT]
	INNER JOIN [dbo].[ACCOUNTS_TRAN_BREAKDOWN] AS [ATB] ON [AT].[TRANSACTION_ID] = [ATB].[TRANSACTION_ID]
	INNER JOIN [dbo].[ACCOUNTS_CLIENT_TRAN_LINK] AS [ACTL] ON  [AT].[TRANSACTION_ID] = [ACTL].[TRANSACTION_ID]
WHERE [ACTL].[POLICY_DETAILS_ID] IN (SELECT [POLICY_DETAILS_ID] FROM @POLICY_DETAILS_ID)
 
-- List client's other Policies (uncomment if needed):
/*
DECLARE @INSURED_PARTY_ID TABLE ([INSURED_PARTY_ID] char(32)) 
INSERT INTO @INSURED_PARTY_ID SELECT DISTINCT [INSURED_PARTY_ID] FROM [CUSTOMER_POLICY_DETAILS] [CPD]
LEFT JOIN [dbo].[CUSTOMER_POLICY_LINK] AS [CPL] ON [CPD].[POLICY_DETAILS_ID] = [CPL].[POLICY_DETAILS_ID] AND [CPD].[HISTORY_ID] = [CPL].[POLICY_DETAILS_HISTORY_ID]
WHERE [CPD].[POLICY_DETAILS_ID] IN (SELECT [POLICY_DETAILS_ID] FROM @POLICY_DETAILS_ID)
 
SELECT [CIP].[SURNAME], [CIP].[INSURED_PARTY_ID], [LPS].[POLICY_STATUS_DEBUG], [cPD].[POLICYNUMBER], [CPD].[POLICYSTARTDATE], [CPD].[POLICYENDDATE], [CPD].[CANCELLATIONDATE], * FROM [dbo].[CUSTOMER_POLICY_DETAILS] AS [CPD]
INNER JOIN [dbo].[LIST_POLICY_STATUS] AS [LPS] ON [CPD].[POLICY_STATUS_ID] = [LPS].[POLICY_STATUS_ID]
LEFT JOIN [dbo].[CUSTOMER_POLICY_LINK] AS [CPL] ON [CPD].[POLICY_DETAILS_ID] = [CPL].[POLICY_DETAILS_ID] AND [CPD].[HISTORY_ID] = [CPL].[POLICY_DETAILS_HISTORY_ID]
LEFT JOIN [dbo].[CUSTOMER_INSURED_PARTY] AS [CIP] ON [CPL].[INSURED_PARTY_ID] = [CIP].[INSURED_PARTY_ID] AND [CPL].[INSURED_PARTY_HISTORY_ID] = [CIP].[HISTORY_ID]
WHERE [CIP].[INSURED_PARTY_ID] IN (SELECT [INSURED_PARTY_ID] FROM @INSURED_PARTY_ID)
--AND [CPD].[POLICYSTARTDATE] > '01 Jan 2020'
ORDER BY [CPD].[POLICY_DETAILS_ID], [CPD].[HISTORY_ID]
*/